### ISSUE TITLE
可以编译出arm64-v8a的么?

### ISSUE THREAD

**Issue by louxinYY** [yuxitong/FFmpegAndroid#1]
如题

**Comment by louxinYY** [comment]
我的错。。。我还引入了另外的文件冲突了。。

**Comment by zhoufeng1213** [comment]
大佬知道怎么配置同时编译出armeabi-v7a、arm64-v8a和x86吗？我配置了application.mk中的APP_ABI 为 
APP_ABI := armeabi-v7a arm64-v8a x86

android.mk中去掉了TARGET_ARCH_ABI
在app.gradle总加入了 abiFilters "armeabi-v7a","arm64-v8a","x86"
编译就直接报错了？
请问大佬是怎么配置编译出arm64-v8a的
